import 'package:hive_flutter/hive_flutter.dart';

// 🛑 CRITICAL: This line links to the generated code that defines UserAdapter.
// Ensure this file exists: 'lib/model/user_model.g.dart'
part 'user_model.g.dart';

// 1. User Data Model
@HiveType(typeId: 0) // typeId must be unique across all Hive models
class User extends HiveObject {
  @HiveField(0)
  String username;

  @HiveField(1)
  String? profileImagePath;

  @HiveField(2)
  int wins;

  @HiveField(3)
  int rank;

  User({required this.username, this.profileImagePath, this.wins = 0, this.rank = 0});

  // Helper method for initial app load
  static User defaultUser() => User(username: "Anonymous", profileImagePath: null, wins: 55, rank: 42);
}

// 2. Hive Initialization Function
// This function is called in main.dart to set up the database.
Future<void> initHive() async {
  // Initializes Hive for Flutter (needed to find the local storage path)
  await Hive.initFlutter();

  // Register the adapter generated by build_runner
  if (!Hive.isAdapterRegistered(0)) {
    Hive.registerAdapter(UserAdapter());
  }

  // Open the box (like a table in SQL) where User objects will be stored
  await Hive.openBox<User>('usersBox');
}
